### ISSUE TITLE
add README.md

### ISSUE THREAD

**Issue by klml** [it-at-m/zammad-ldap-sync#11]
Improve [README.md](https://github.com/it-at-m/zammad-ldap-sync/blob/dev/README.md)

* Add a description from your project here.
* reason why we dont use [zammad.org integrations/ldap/](https://admin-docs.zammad.org/en/latest/system/integrations/ldap/index.html#limitations)
  * Mapping / Synchronizing organizations is not possible
  * Nested groups are not supported.
  * When a user originates from an LDAP server, Zammad will try to verify the login credentials against LDAP first --> no SSO

**Comment by sfi2022** [comment]
@rowe42 : Please update documentation as far as possible in branch :  https://github.com/it-at-m/zammad-ldap-sync/tree/documentation
