### ISSUE TITLE
rermove mpdz

### ISSUE THREAD

**Issue by klml** [it-at-m/zammad-ldap-sync#23]
**Describe the bug**
[de.muenchen.mpdz.zammad.ldap.service](https://github.com/search?q=repo%3Ait-at-m%2Fzammad-ldap-sync%20de.muenchen.mpdz.zammad.ldap.service&type=code) consists mpdz

Change to `de.muenchen.zammad.ldap.service`

**Comment by klml** [comment]
@FabianWilms your opinion?

**Comment by FabianWilms** [comment]
I will do the same thing with our other services as soon as we start the renaming.

**Comment by sfi2022** [comment]
Removed from package name.

**Comment by klml** [comment]
https://github.com/it-at-m/zammad-ldap-sync/commit/8b80339973ef0d94652355d378652222b6c7a41d
